Rasa process starting
Rasa process starting
Restoring parameters from models/nlu/current/intent_classifier_tensorflow_embedding.ckpt
Available web server routes: 
hello                                              HEAD, OPTIONS, GET             /
list_trackers                                      HEAD, OPTIONS, GET             /conversations
execute_action                                     OPTIONS, POST                  /conversations/[sender_id]/execute
log_message                                        OPTIONS, POST                  /conversations/[sender_id]/messages
predict                                            OPTIONS, POST                  /conversations/[sender_id]/predict
respond                                            HEAD, OPTIONS, POST, GET       /conversations/[sender_id]/respond
retrieve_story                                     HEAD, OPTIONS, GET             /conversations/[sender_id]/story
retrieve_tracker                                   HEAD, OPTIONS, GET             /conversations/[sender_id]/tracker
replace_events                                     PUT, OPTIONS                   /conversations/[sender_id]/tracker/events
get_domain                                         HEAD, OPTIONS, GET             /domain
evaluate_stories                                   OPTIONS, POST                  /evaluate
continue_training                                  OPTIONS, POST                  /finetune
load_model                                         OPTIONS, POST                  /model
tracker_predict                                    OPTIONS, POST                  /predict
static                                             HEAD, OPTIONS, GET             /static/[filename]
status                                             HEAD, OPTIONS, GET             /status
version                                            HEAD, OPTIONS, GET             /version
custom_webhook_CmdlineInput.health                 HEAD, OPTIONS, GET             /webhooks/rest/
custom_webhook_CmdlineInput.receive                OPTIONS, POST                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'user'.
Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.9230203032493591}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 
	color: None
Current tracker state [None, None, None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '7'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'utter_greet' with prob 1.00.
Action 'utter_greet' ended with events '[]'
Bot utterance 'BotUttered(text: Hey there! :) What is your favorite color?, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [None, None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '0'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'user'
Received user message 'red' with intent '{'name': 'provide_color', 'confidence': 0.9511568546295166}' and entities '[{'start': 0, 'end': 3, 'value': 'red', 'entity': 'color', 'confidence': 0.8991835171123593, 'extractor': 'ner_crf'}]'
Logged UserUtterance - tracker now has 7 events
Current slot values: 
	color: red
Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'intent_provide_color': 1.0, 'entity_color': 1.0, 'slot_color_0': 1.0, 'prev_action_listen': 1.0}]
There is no memorised next action
There is no active form
Predicted next action using policy_1_FallbackPolicy
Predicted next action 'action_default_fallback' with prob 1.00.
Action 'action_default_fallback' ended with events '['UserUtteranceReverted()']'
Current tracker state [None, None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '0'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'user'
Received user message 'green' with intent '{'name': 'provide_color', 'confidence': 0.9612888693809509}' and entities '[{'start': 0, 'end': 5, 'value': 'green', 'entity': 'color', 'confidence': 0.9108570899993783, 'extractor': 'ner_crf'}]'
Logged UserUtterance - tracker now has 12 events
Current slot values: 
	color: green
Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'intent_provide_color': 1.0, 'entity_color': 1.0, 'slot_color_0': 1.0, 'prev_action_listen': 1.0}]
There is no memorised next action
There is no active form
Predicted next action using policy_1_FallbackPolicy
Predicted next action 'action_default_fallback' with prob 1.00.
Action 'action_default_fallback' ended with events '['UserUtteranceReverted()']'
Current tracker state [None, None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '0'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Rasa process starting
Restoring parameters from models/nlu/current/intent_classifier_tensorflow_embedding.ckpt
Available web server routes: 
hello                                              HEAD, GET, OPTIONS             /
list_trackers                                      HEAD, GET, OPTIONS             /conversations
execute_action                                     POST, OPTIONS                  /conversations/[sender_id]/execute
log_message                                        POST, OPTIONS                  /conversations/[sender_id]/messages
predict                                            POST, OPTIONS                  /conversations/[sender_id]/predict
respond                                            HEAD, POST, GET, OPTIONS       /conversations/[sender_id]/respond
retrieve_story                                     HEAD, GET, OPTIONS             /conversations/[sender_id]/story
retrieve_tracker                                   HEAD, GET, OPTIONS             /conversations/[sender_id]/tracker
replace_events                                     OPTIONS, PUT                   /conversations/[sender_id]/tracker/events
get_domain                                         HEAD, GET, OPTIONS             /domain
evaluate_stories                                   POST, OPTIONS                  /evaluate
continue_training                                  POST, OPTIONS                  /finetune
load_model                                         POST, OPTIONS                  /model
tracker_predict                                    POST, OPTIONS                  /predict
static                                             HEAD, GET, OPTIONS             /static/[filename]
status                                             HEAD, GET, OPTIONS             /status
version                                            HEAD, GET, OPTIONS             /version
custom_webhook_CmdlineInput.health                 HEAD, GET, OPTIONS             /webhooks/rest/
custom_webhook_CmdlineInput.receive                POST, OPTIONS                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'user'.
Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.9566079378128052}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 

Current tracker state [None, None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '7'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'utter_greet' with prob 1.00.
Action 'utter_greet' ended with events '[]'
Bot utterance 'BotUttered(text: Hey there! :) What is your favorite color?, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}]
There is a memorised next action '0'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'user'
Received user message 'green' with intent '{'name': 'provide_color', 'confidence': 0.9799908399581909}' and entities '[{'start': 0, 'end': 5, 'value': 'green', 'entity': 'color', 'confidence': 0.9108570899993783, 'extractor': 'ner_crf'}]'
Logged UserUtterance - tracker now has 6 events
Current slot values: 

Current tracker state [None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'entity_color': 1.0, 'prev_action_listen': 1.0, 'intent_provide_color': 1.0}]
There is no memorised next action
There is no active form
Action 'action_listen' was predicted after a user message using policy_0_KerasPolicy. Predicting fallback action: action_default_fallback
Predicted next action using policy_1_FallbackPolicy
Predicted next action 'action_default_fallback' with prob 1.00.
Action 'action_default_fallback' ended with events '['UserUtteranceReverted()']'
Current tracker state [None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}]
There is a memorised next action '0'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Rasa process starting
Restoring parameters from models/nlu/current/intent_classifier_tensorflow_embedding.ckpt
Available web server routes: 
hello                                              GET, OPTIONS, HEAD             /
list_trackers                                      GET, OPTIONS, HEAD             /conversations
execute_action                                     OPTIONS, POST                  /conversations/[sender_id]/execute
log_message                                        OPTIONS, POST                  /conversations/[sender_id]/messages
predict                                            OPTIONS, POST                  /conversations/[sender_id]/predict
respond                                            GET, OPTIONS, POST, HEAD       /conversations/[sender_id]/respond
retrieve_story                                     GET, OPTIONS, HEAD             /conversations/[sender_id]/story
retrieve_tracker                                   GET, OPTIONS, HEAD             /conversations/[sender_id]/tracker
replace_events                                     PUT, OPTIONS                   /conversations/[sender_id]/tracker/events
get_domain                                         GET, OPTIONS, HEAD             /domain
evaluate_stories                                   OPTIONS, POST                  /evaluate
continue_training                                  OPTIONS, POST                  /finetune
load_model                                         OPTIONS, POST                  /model
tracker_predict                                    OPTIONS, POST                  /predict
static                                             GET, OPTIONS, HEAD             /static/[filename]
status                                             GET, OPTIONS, HEAD             /status
version                                            GET, OPTIONS, HEAD             /version
custom_webhook_CmdlineInput.health                 GET, OPTIONS, HEAD             /webhooks/rest/
custom_webhook_CmdlineInput.receive                OPTIONS, POST                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'user'.
Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.9630599021911621}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 
	color: None
Current tracker state [None, None, None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '7'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'utter_greet' with prob 1.00.
Action 'utter_greet' ended with events '[]'
Bot utterance 'BotUttered(text: Hey there! :) What is your favorite color?, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [None, None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}]
There is a memorised next action '0'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'user'
Received user message 'green' with intent '{'name': 'provide_color', 'confidence': 0.964526355266571}' and entities '[{'start': 0, 'end': 5, 'value': 'green', 'entity': 'color', 'confidence': 0.9108570899993783, 'extractor': 'ner_crf'}]'
Logged UserUtterance - tracker now has 7 events
Current slot values: 
	color: green
Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'slot_color_0': 1.0, 'prev_action_listen': 1.0, 'entity_color': 1.0, 'intent_provide_color': 1.0}]
There is a memorised next action '8'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'utter_color' with prob 1.00.
Action 'utter_color' ended with events '[]'
Bot utterance 'BotUttered(text: Your favorite color is green., data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [{}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'slot_color_0': 1.0, 'prev_action_listen': 1.0, 'entity_color': 1.0, 'intent_provide_color': 1.0}, {'slot_color_0': 1.0, 'entity_color': 1.0, 'intent_provide_color': 1.0, 'prev_utter_color': 1.0}]
There is a memorised next action '9'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'utter_bye' with prob 1.00.
Action 'utter_bye' ended with events '[]'
Bot utterance 'BotUttered(text: Bye, thanks for chatting with color bot!, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [{'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'slot_color_0': 1.0, 'prev_action_listen': 1.0, 'entity_color': 1.0, 'intent_provide_color': 1.0}, {'slot_color_0': 1.0, 'entity_color': 1.0, 'intent_provide_color': 1.0, 'prev_utter_color': 1.0}, {'prev_utter_bye': 1.0, 'slot_color_0': 1.0, 'entity_color': 1.0, 'intent_provide_color': 1.0}]
There is a memorised next action '0'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Rasa process starting
Restoring parameters from models/nlu/current/intent_classifier_tensorflow_embedding.ckpt
Available web server routes: 
hello                                              HEAD, OPTIONS, GET             /
list_trackers                                      HEAD, OPTIONS, GET             /conversations
execute_action                                     POST, OPTIONS                  /conversations/[sender_id]/execute
log_message                                        POST, OPTIONS                  /conversations/[sender_id]/messages
predict                                            POST, OPTIONS                  /conversations/[sender_id]/predict
respond                                            HEAD, POST, OPTIONS, GET       /conversations/[sender_id]/respond
retrieve_story                                     HEAD, OPTIONS, GET             /conversations/[sender_id]/story
retrieve_tracker                                   HEAD, OPTIONS, GET             /conversations/[sender_id]/tracker
replace_events                                     OPTIONS, PUT                   /conversations/[sender_id]/tracker/events
get_domain                                         HEAD, OPTIONS, GET             /domain
evaluate_stories                                   POST, OPTIONS                  /evaluate
continue_training                                  POST, OPTIONS                  /finetune
load_model                                         POST, OPTIONS                  /model
tracker_predict                                    POST, OPTIONS                  /predict
static                                             HEAD, OPTIONS, GET             /static/[filename]
status                                             HEAD, OPTIONS, GET             /status
version                                            HEAD, OPTIONS, GET             /version
custom_webhook_CmdlineInput.health                 HEAD, OPTIONS, GET             /webhooks/rest/
custom_webhook_CmdlineInput.receive                POST, OPTIONS                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'user'.
Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.9823233485221863}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 

Current tracker state [None, None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '7'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'utter_greet' with prob 1.00.
Action 'utter_greet' ended with events '[]'
Bot utterance 'BotUttered(text: Hey there! :) What is your favorite color?, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}]
There is a memorised next action '0'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'user'
Received user message 'green' with intent '{'name': 'provide_color', 'confidence': 0.9737006425857544}' and entities '[{'start': 0, 'end': 5, 'value': 'green', 'entity': 'color', 'confidence': 0.9108570899993783, 'extractor': 'ner_crf'}]'
Logged UserUtterance - tracker now has 6 events
Current slot values: 

Current tracker state [None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}]
There is a memorised next action '8'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'utter_color' with prob 1.00.
Action 'utter_color' ended with events '[]'
Bot utterance 'BotUttered(text: Your favorite color is {color}., data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [{}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}, {'prev_utter_color': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}]
There is a memorised next action '9'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'utter_bye' with prob 1.00.
Action 'utter_bye' ended with events '[]'
Bot utterance 'BotUttered(text: Bye, thanks for chatting with color bot!, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [{'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}, {'prev_utter_color': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}, {'prev_utter_bye': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}]
There is a memorised next action '0'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'user'
Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.9823233485221863}' and entities '[]'
Logged UserUtterance - tracker now has 12 events
Current slot values: 

Current tracker state [{'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}, {'prev_utter_color': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}, {'prev_utter_bye': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '7'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'utter_greet' with prob 1.00.
Action 'utter_greet' ended with events '[]'
Bot utterance 'BotUttered(text: Hey there! :) What is your favorite color?, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [{'prev_action_listen': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}, {'prev_utter_color': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}, {'prev_utter_bye': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}]
There is a memorised next action '0'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'user'
Received user message 'red' with intent '{'name': 'provide_color', 'confidence': 0.9667075872421265}' and entities '[{'start': 0, 'end': 3, 'value': 'red', 'entity': 'color', 'confidence': 0.8991835171123593, 'extractor': 'ner_crf'}]'
Logged UserUtterance - tracker now has 16 events
Current slot values: 

Current tracker state [{'prev_utter_color': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}, {'prev_utter_bye': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}]
There is a memorised next action '8'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'utter_color' with prob 1.00.
Action 'utter_color' ended with events '[]'
Bot utterance 'BotUttered(text: Your favorite color is {color}., data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [{'prev_utter_bye': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}, {'prev_utter_color': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}]
There is a memorised next action '9'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'utter_bye' with prob 1.00.
Action 'utter_bye' ended with events '[]'
Bot utterance 'BotUttered(text: Bye, thanks for chatting with color bot!, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [{'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}, {'prev_utter_color': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}, {'prev_utter_bye': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}]
There is a memorised next action '0'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
Looking for jobs to run
No jobs; waiting until a job is added
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Available web server routes: 
hello                                              HEAD, OPTIONS, GET             /
list_trackers                                      HEAD, OPTIONS, GET             /conversations
execute_action                                     POST, OPTIONS                  /conversations/[sender_id]/execute
log_message                                        POST, OPTIONS                  /conversations/[sender_id]/messages
predict                                            POST, OPTIONS                  /conversations/[sender_id]/predict
respond                                            POST, OPTIONS, GET, HEAD       /conversations/[sender_id]/respond
retrieve_story                                     HEAD, OPTIONS, GET             /conversations/[sender_id]/story
retrieve_tracker                                   HEAD, OPTIONS, GET             /conversations/[sender_id]/tracker
replace_events                                     OPTIONS, PUT                   /conversations/[sender_id]/tracker/events
get_domain                                         HEAD, OPTIONS, GET             /domain
evaluate_stories                                   POST, OPTIONS                  /evaluate
continue_training                                  POST, OPTIONS                  /finetune
load_model                                         POST, OPTIONS                  /model
parse                                              POST, OPTIONS                  /parse
tracker_predict                                    POST, OPTIONS                  /predict
static                                             HEAD, OPTIONS, GET             /static/[filename]
status                                             HEAD, OPTIONS, GET             /status
version                                            HEAD, OPTIONS, GET             /version
custom_webhook_CmdlineInput.health                 HEAD, OPTIONS, GET             /webhooks/rest/
custom_webhook_CmdlineInput.receive                POST, OPTIONS                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.9751318693161011}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 
	color: None
Current tracker state [None, None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '8'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'utter_greet' with prob 1.00.
Action 'utter_greet' ended with events '[]'
Bot utterance 'BotUttered(text: Hey there! :) What is your favorite color?, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}]
There is a memorised next action '0'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'my favorite color is black' with intent '{'name': 'provide_color', 'confidence': 0.9613914489746094}' and entities '[{'start': 21, 'end': 26, 'value': 'black', 'entity': 'color', 'confidence': 0.8826586546832239, 'extractor': 'CRFEntityExtractor'}]'
Logged UserUtterance - tracker now has 7 events
Current slot values: 
	color: black
Current tracker state [None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'slot_color_0': 1.0, 'intent_provide_color': 1.0, 'prev_action_listen': 1.0, 'entity_color': 1.0}]
There is a memorised next action '9'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'utter_color' with prob 1.00.
Action 'utter_color' ended with events '[]'
Bot utterance 'BotUttered(text: Your favorite color is black., data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [{}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'slot_color_0': 1.0, 'intent_provide_color': 1.0, 'prev_action_listen': 1.0, 'entity_color': 1.0}, {'slot_color_0': 1.0, 'prev_utter_color': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}]
There is a memorised next action '10'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'utter_bye' with prob 1.00.
Action 'utter_bye' ended with events '[]'
Bot utterance 'BotUttered(text: Bye, thanks for chatting with color bot!, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [{'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'slot_color_0': 1.0, 'intent_provide_color': 1.0, 'prev_action_listen': 1.0, 'entity_color': 1.0}, {'slot_color_0': 1.0, 'prev_utter_color': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}, {'slot_color_0': 1.0, 'prev_utter_bye': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}]
There is a memorised next action '0'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'bye' with intent '{'name': None, 'confidence': 0.0}' and entities '[]'
Logged UserUtterance - tracker now has 13 events
Current slot values: 
	color: black
NLU confidence 0.0 is lower than NLU threshold 0.3. 
Current tracker state [{'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'slot_color_0': 1.0, 'intent_provide_color': 1.0, 'prev_action_listen': 1.0, 'entity_color': 1.0}, {'slot_color_0': 1.0, 'prev_utter_color': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}, {'slot_color_0': 1.0, 'prev_utter_bye': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}, {'slot_color_0': 1.0, 'prev_action_listen': 1.0}]
There is no memorised next action
There is no active form
Predicted next action using policy_1_FallbackPolicy
Predicted next action 'action_default_fallback' with prob 1.00.
Action 'action_default_fallback' ended with events '['UserUtteranceReverted()']'
Current tracker state [{'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'slot_color_0': 1.0, 'intent_provide_color': 1.0, 'prev_action_listen': 1.0, 'entity_color': 1.0}, {'slot_color_0': 1.0, 'prev_utter_color': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}, {'slot_color_0': 1.0, 'prev_utter_bye': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}]
There is a memorised next action '0'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'bye bye' with intent '{'name': None, 'confidence': 0.0}' and entities '[]'
Logged UserUtterance - tracker now has 17 events
Current slot values: 
	color: black
NLU confidence 0.0 is lower than NLU threshold 0.3. 
Current tracker state [{'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'slot_color_0': 1.0, 'intent_provide_color': 1.0, 'prev_action_listen': 1.0, 'entity_color': 1.0}, {'slot_color_0': 1.0, 'prev_utter_color': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}, {'slot_color_0': 1.0, 'prev_utter_bye': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}, {'slot_color_0': 1.0, 'prev_action_listen': 1.0}]
There is no memorised next action
There is no active form
Predicted next action using policy_1_FallbackPolicy
Predicted next action 'action_default_fallback' with prob 1.00.
Action 'action_default_fallback' ended with events '['UserUtteranceReverted()']'
Current tracker state [{'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'slot_color_0': 1.0, 'intent_provide_color': 1.0, 'prev_action_listen': 1.0, 'entity_color': 1.0}, {'slot_color_0': 1.0, 'prev_utter_color': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}, {'slot_color_0': 1.0, 'prev_utter_bye': 1.0, 'intent_provide_color': 1.0, 'entity_color': 1.0}]
There is a memorised next action '0'
There is no active form
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
Looking for jobs to run
No jobs; waiting until a job is added
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Available web server routes: 
hello                                              HEAD, OPTIONS, GET             /
list_trackers                                      HEAD, OPTIONS, GET             /conversations
execute_action                                     OPTIONS, POST                  /conversations/[sender_id]/execute
log_message                                        OPTIONS, POST                  /conversations/[sender_id]/messages
predict                                            OPTIONS, POST                  /conversations/[sender_id]/predict
respond                                            HEAD, OPTIONS, GET, POST       /conversations/[sender_id]/respond
retrieve_story                                     HEAD, OPTIONS, GET             /conversations/[sender_id]/story
retrieve_tracker                                   HEAD, OPTIONS, GET             /conversations/[sender_id]/tracker
replace_events                                     OPTIONS, PUT                   /conversations/[sender_id]/tracker/events
get_domain                                         HEAD, OPTIONS, GET             /domain
evaluate_stories                                   OPTIONS, POST                  /evaluate
continue_training                                  OPTIONS, POST                  /finetune
load_model                                         OPTIONS, POST                  /model
parse                                              OPTIONS, POST                  /parse
tracker_predict                                    OPTIONS, POST                  /predict
static                                             HEAD, OPTIONS, GET             /static/[filename]
status                                             HEAD, OPTIONS, GET             /status
version                                            HEAD, OPTIONS, GET             /version
custom_webhook_CmdlineInput.health                 HEAD, OPTIONS, GET             /webhooks/rest/
custom_webhook_CmdlineInput.receive                OPTIONS, POST                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.9625009894371033}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 
	specialist: None
Current tracker state [None, None, None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '8'
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'utter_greet' with prob 1.00.
Action 'utter_greet' ended with events '[]'
Bot utterance 'BotUttered(text: Hi! What can I do for you?, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [None, None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'get me a dentist' with intent '{'name': 'inform', 'confidence': 0.9424940347671509}' and entities '[{'start': 9, 'end': 16, 'value': 'dentist', 'entity': 'specialist', 'confidence': 0.9915488283977238, 'extractor': 'CRFEntityExtractor'}]'
Logged UserUtterance - tracker now has 7 events
Current slot values: 
	specialist: dentist
Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'entity_specialist': 1.0, 'prev_action_listen': 1.0, 'slot_specialist_0': 1.0, 'intent_inform': 1.0}]
There is no memorised next action
Predicted next action using policy_0_KerasPolicy
Predicted next action 'action_appointment' with prob 0.32.
Calling action endpoint to run action 'action_appointment'.
Failed to run custom action 'action_appointment'. Couldn't connect to the server at 'http://localhost:5055/webhook'. Is the server running? Error: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f792049ebe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/zoro/anaconda3/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/zoro/anaconda3/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/zoro/anaconda3/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/zoro/anaconda3/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/home/zoro/anaconda3/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 196, in connect
    conn = self._new_conn()
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f792049ebe0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f792049ebe0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/rasa_core/actions/action.py", line 381, in run
    json=json, method="post", timeout=DEFAULT_REQUEST_TIMEOUT)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/rasa_core/utils.py", line 702, in request
    **kwargs)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f792049ebe0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/rasa_core/processor.py", line 345, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/rasa_core/actions/action.py", line 402, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Action 'action_appointment' ended with events '[]'
Current tracker state [{}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'entity_specialist': 1.0, 'prev_action_listen': 1.0, 'slot_specialist_0': 1.0, 'intent_inform': 1.0}, {'entity_specialist': 1.0, 'prev_action_appointment': 1.0, 'slot_specialist_0': 1.0, 'intent_inform': 1.0}]
There is no memorised next action
Predicted next action using policy_0_KerasPolicy
Predicted next action 'action_listen' with prob 0.86.
Action 'action_listen' ended with events '[]'
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
Looking for jobs to run
No jobs; waiting until a job is added
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Available web server routes: 
hello                                              GET, HEAD, OPTIONS             /
list_trackers                                      GET, HEAD, OPTIONS             /conversations
execute_action                                     OPTIONS, POST                  /conversations/[sender_id]/execute
log_message                                        OPTIONS, POST                  /conversations/[sender_id]/messages
predict                                            OPTIONS, POST                  /conversations/[sender_id]/predict
respond                                            GET, HEAD, OPTIONS, POST       /conversations/[sender_id]/respond
retrieve_story                                     GET, HEAD, OPTIONS             /conversations/[sender_id]/story
retrieve_tracker                                   GET, HEAD, OPTIONS             /conversations/[sender_id]/tracker
replace_events                                     PUT, OPTIONS                   /conversations/[sender_id]/tracker/events
get_domain                                         GET, HEAD, OPTIONS             /domain
evaluate_stories                                   OPTIONS, POST                  /evaluate
continue_training                                  OPTIONS, POST                  /finetune
load_model                                         OPTIONS, POST                  /model
parse                                              OPTIONS, POST                  /parse
tracker_predict                                    OPTIONS, POST                  /predict
static                                             GET, HEAD, OPTIONS             /static/[filename]
status                                             GET, HEAD, OPTIONS             /status
version                                            GET, HEAD, OPTIONS             /version
custom_webhook_CmdlineInput.health                 GET, HEAD, OPTIONS             /webhooks/rest/
custom_webhook_CmdlineInput.receive                OPTIONS, POST                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.9625009894371033}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 
	specialist: None
Current tracker state [None, None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '8'
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'utter_greet' with prob 1.00.
Action 'utter_greet' ended with events '[]'
Bot utterance 'BotUttered(text: Hello! How can I help?, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'get me a dentist' with intent '{'name': 'inform', 'confidence': 0.9424940347671509}' and entities '[{'start': 9, 'end': 16, 'value': 'dentist', 'entity': 'specialist', 'confidence': 0.9915488283977238, 'extractor': 'CRFEntityExtractor'}]'
Logged UserUtterance - tracker now has 7 events
Current slot values: 
	specialist: dentist
Current tracker state [None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'intent_inform': 1.0, 'entity_specialist': 1.0, 'slot_specialist_0': 1.0, 'prev_action_listen': 1.0}]
There is no memorised next action
Predicted next action using policy_0_KerasPolicy
Predicted next action 'action_appointment' with prob 0.32.
Calling action endpoint to run action 'action_appointment'.
Failed to run custom action 'action_appointment'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/rasa_core/actions/action.py", line 392, in run
    response.raise_for_status()
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/rasa_core/processor.py", line 345, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/rasa_core/actions/action.py", line 412, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Action 'action_appointment' ended with events '[]'
Current tracker state [{}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'intent_inform': 1.0, 'entity_specialist': 1.0, 'slot_specialist_0': 1.0, 'prev_action_listen': 1.0}, {'prev_action_appointment': 1.0, 'intent_inform': 1.0, 'entity_specialist': 1.0, 'slot_specialist_0': 1.0}]
There is no memorised next action
Predicted next action using policy_0_KerasPolicy
Predicted next action 'action_listen' with prob 0.86.
Action 'action_listen' ended with events '[]'
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
Looking for jobs to run
No jobs; waiting until a job is added
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Available web server routes: 
hello                                              HEAD, OPTIONS, GET             /
list_trackers                                      HEAD, OPTIONS, GET             /conversations
execute_action                                     POST, OPTIONS                  /conversations/[sender_id]/execute
log_message                                        POST, OPTIONS                  /conversations/[sender_id]/messages
predict                                            POST, OPTIONS                  /conversations/[sender_id]/predict
respond                                            HEAD, POST, OPTIONS, GET       /conversations/[sender_id]/respond
retrieve_story                                     HEAD, OPTIONS, GET             /conversations/[sender_id]/story
retrieve_tracker                                   HEAD, OPTIONS, GET             /conversations/[sender_id]/tracker
replace_events                                     PUT, OPTIONS                   /conversations/[sender_id]/tracker/events
get_domain                                         HEAD, OPTIONS, GET             /domain
evaluate_stories                                   POST, OPTIONS                  /evaluate
continue_training                                  POST, OPTIONS                  /finetune
load_model                                         POST, OPTIONS                  /model
parse                                              POST, OPTIONS                  /parse
tracker_predict                                    POST, OPTIONS                  /predict
static                                             HEAD, OPTIONS, GET             /static/[filename]
status                                             HEAD, OPTIONS, GET             /status
version                                            HEAD, OPTIONS, GET             /version
custom_webhook_CmdlineInput.health                 HEAD, OPTIONS, GET             /webhooks/rest/
custom_webhook_CmdlineInput.receive                POST, OPTIONS                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.9625009894371033}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 
	specialist: None
Current tracker state [None, None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '8'
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'utter_greet' with prob 1.00.
Action 'utter_greet' ended with events '[]'
Bot utterance 'BotUttered(text: Hi! What can I do for you?, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'get me a dentist' with intent '{'name': 'inform', 'confidence': 0.9424940347671509}' and entities '[{'start': 9, 'end': 16, 'value': 'dentist', 'entity': 'specialist', 'confidence': 0.9915488283977238, 'extractor': 'CRFEntityExtractor'}]'
Logged UserUtterance - tracker now has 7 events
Current slot values: 
	specialist: dentist
Current tracker state [None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'intent_inform': 1.0, 'slot_specialist_0': 1.0, 'entity_specialist': 1.0, 'prev_action_listen': 1.0}]
There is no memorised next action
Predicted next action using policy_0_KerasPolicy
Predicted next action 'action_appointment' with prob 0.32.
Calling action endpoint to run action 'action_appointment'.
Failed to run custom action 'action_appointment'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/rasa_core/actions/action.py", line 392, in run
    response.raise_for_status()
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/rasa_core/processor.py", line 345, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/rasa_core/actions/action.py", line 412, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Action 'action_appointment' ended with events '[]'
Current tracker state [{}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'intent_inform': 1.0, 'slot_specialist_0': 1.0, 'entity_specialist': 1.0, 'prev_action_listen': 1.0}, {'intent_inform': 1.0, 'prev_action_appointment': 1.0, 'slot_specialist_0': 1.0, 'entity_specialist': 1.0}]
There is no memorised next action
Predicted next action using policy_0_KerasPolicy
Predicted next action 'action_listen' with prob 0.86.
Action 'action_listen' ended with events '[]'
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
Looking for jobs to run
No jobs; waiting until a job is added
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Available web server routes: 
hello                                              HEAD, GET, OPTIONS             /
list_trackers                                      HEAD, GET, OPTIONS             /conversations
execute_action                                     POST, OPTIONS                  /conversations/[sender_id]/execute
log_message                                        POST, OPTIONS                  /conversations/[sender_id]/messages
predict                                            POST, OPTIONS                  /conversations/[sender_id]/predict
respond                                            HEAD, POST, GET, OPTIONS       /conversations/[sender_id]/respond
retrieve_story                                     HEAD, GET, OPTIONS             /conversations/[sender_id]/story
retrieve_tracker                                   HEAD, GET, OPTIONS             /conversations/[sender_id]/tracker
replace_events                                     PUT, OPTIONS                   /conversations/[sender_id]/tracker/events
get_domain                                         HEAD, GET, OPTIONS             /domain
evaluate_stories                                   POST, OPTIONS                  /evaluate
continue_training                                  POST, OPTIONS                  /finetune
load_model                                         POST, OPTIONS                  /model
parse                                              POST, OPTIONS                  /parse
tracker_predict                                    POST, OPTIONS                  /predict
static                                             HEAD, GET, OPTIONS             /static/[filename]
status                                             HEAD, GET, OPTIONS             /status
version                                            HEAD, GET, OPTIONS             /version
custom_webhook_CmdlineInput.health                 HEAD, GET, OPTIONS             /webhooks/rest/
custom_webhook_CmdlineInput.receive                POST, OPTIONS                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.9625009894371033}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 
	specialist: None
Current tracker state [None, None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '8'
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'utter_greet' with prob 1.00.
Action 'utter_greet' ended with events '[]'
Bot utterance 'BotUttered(text: Hello! How can I help?, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'get me a dentist' with intent '{'name': 'inform', 'confidence': 0.9424940347671509}' and entities '[{'start': 9, 'end': 16, 'value': 'dentist', 'entity': 'specialist', 'confidence': 0.9915488283977238, 'extractor': 'CRFEntityExtractor'}]'
Logged UserUtterance - tracker now has 7 events
Current slot values: 
	specialist: dentist
Current tracker state [None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'entity_specialist': 1.0, 'slot_specialist_0': 1.0, 'intent_inform': 1.0, 'prev_action_listen': 1.0}]
There is no memorised next action
Predicted next action using policy_0_KerasPolicy
Predicted next action 'action_appointment' with prob 0.32.
Calling action endpoint to run action 'action_appointment'.
Failed to run custom action 'action_appointment'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/rasa_core/actions/action.py", line 392, in run
    response.raise_for_status()
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/rasa_core/processor.py", line 345, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/rasa_core/actions/action.py", line 412, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Action 'action_appointment' ended with events '[]'
Current tracker state [{}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'entity_specialist': 1.0, 'slot_specialist_0': 1.0, 'intent_inform': 1.0, 'prev_action_listen': 1.0}, {'entity_specialist': 1.0, 'slot_specialist_0': 1.0, 'intent_inform': 1.0, 'prev_action_appointment': 1.0}]
There is no memorised next action
Predicted next action using policy_0_KerasPolicy
Predicted next action 'action_listen' with prob 0.86.
Action 'action_listen' ended with events '[]'
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
Looking for jobs to run
No jobs; waiting until a job is added
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
Looking for jobs to run
No jobs; waiting until a job is added
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Available web server routes: 
hello                                              OPTIONS, HEAD, GET             /
list_trackers                                      OPTIONS, HEAD, GET             /conversations
execute_action                                     OPTIONS, POST                  /conversations/[sender_id]/execute
log_message                                        OPTIONS, POST                  /conversations/[sender_id]/messages
predict                                            OPTIONS, POST                  /conversations/[sender_id]/predict
respond                                            OPTIONS, HEAD, POST, GET       /conversations/[sender_id]/respond
retrieve_story                                     OPTIONS, HEAD, GET             /conversations/[sender_id]/story
retrieve_tracker                                   OPTIONS, HEAD, GET             /conversations/[sender_id]/tracker
replace_events                                     OPTIONS, PUT                   /conversations/[sender_id]/tracker/events
get_domain                                         OPTIONS, HEAD, GET             /domain
evaluate_stories                                   OPTIONS, POST                  /evaluate
continue_training                                  OPTIONS, POST                  /finetune
load_model                                         OPTIONS, POST                  /model
parse                                              OPTIONS, POST                  /parse
tracker_predict                                    OPTIONS, POST                  /predict
static                                             OPTIONS, HEAD, GET             /static/[filename]
status                                             OPTIONS, HEAD, GET             /status
version                                            OPTIONS, HEAD, GET             /version
custom_webhook_CmdlineInput.health                 OPTIONS, HEAD, GET             /webhooks/rest/
custom_webhook_CmdlineInput.receive                OPTIONS, POST                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.9625009894371033}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 
	specialist: None
Current tracker state [None, None, None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '8'
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'utter_greet' with prob 1.00.
Action 'utter_greet' ended with events '[]'
Bot utterance 'BotUttered(text: Hi! What can I do for you?, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [None, None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'get me a dentist' with intent '{'name': 'inform', 'confidence': 0.9424940347671509}' and entities '[{'start': 9, 'end': 16, 'value': 'dentist', 'entity': 'specialist', 'confidence': 0.9915488283977238, 'extractor': 'CRFEntityExtractor'}]'
Logged UserUtterance - tracker now has 7 events
Current slot values: 
	specialist: dentist
Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'entity_specialist': 1.0, 'prev_action_listen': 1.0, 'intent_inform': 1.0, 'slot_specialist_0': 1.0}]
There is no memorised next action
Predicted next action using policy_0_KerasPolicy
Predicted next action 'action_appointment' with prob 0.32.
Calling action endpoint to run action 'action_appointment'.
Failed to run custom action 'action_appointment'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/rasa_core/actions/action.py", line 393, in run
    response.raise_for_status()
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/rasa_core/processor.py", line 345, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/rasa_core/actions/action.py", line 413, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Action 'action_appointment' ended with events '[]'
Current tracker state [{}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'entity_specialist': 1.0, 'prev_action_listen': 1.0, 'intent_inform': 1.0, 'slot_specialist_0': 1.0}, {'entity_specialist': 1.0, 'intent_inform': 1.0, 'prev_action_appointment': 1.0, 'slot_specialist_0': 1.0}]
There is no memorised next action
Predicted next action using policy_0_KerasPolicy
Predicted next action 'action_listen' with prob 0.86.
Action 'action_listen' ended with events '[]'
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
Looking for jobs to run
No jobs; waiting until a job is added
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Available web server routes: 
hello                                              OPTIONS, HEAD, GET             /
list_trackers                                      OPTIONS, HEAD, GET             /conversations
execute_action                                     POST, OPTIONS                  /conversations/[sender_id]/execute
log_message                                        POST, OPTIONS                  /conversations/[sender_id]/messages
predict                                            POST, OPTIONS                  /conversations/[sender_id]/predict
respond                                            POST, OPTIONS, HEAD, GET       /conversations/[sender_id]/respond
retrieve_story                                     OPTIONS, HEAD, GET             /conversations/[sender_id]/story
retrieve_tracker                                   OPTIONS, HEAD, GET             /conversations/[sender_id]/tracker
replace_events                                     OPTIONS, PUT                   /conversations/[sender_id]/tracker/events
get_domain                                         OPTIONS, HEAD, GET             /domain
evaluate_stories                                   POST, OPTIONS                  /evaluate
continue_training                                  POST, OPTIONS                  /finetune
load_model                                         POST, OPTIONS                  /model
parse                                              POST, OPTIONS                  /parse
tracker_predict                                    POST, OPTIONS                  /predict
static                                             OPTIONS, HEAD, GET             /static/[filename]
status                                             OPTIONS, HEAD, GET             /status
version                                            OPTIONS, HEAD, GET             /version
custom_webhook_CmdlineInput.health                 OPTIONS, HEAD, GET             /webhooks/rest/
custom_webhook_CmdlineInput.receive                POST, OPTIONS                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.9625009894371033}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 
	specialist: None
Current tracker state [None, None, None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '8'
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'utter_greet' with prob 1.00.
Action 'utter_greet' ended with events '[]'
Bot utterance 'BotUttered(text: Hi! What can I do for you?, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [None, None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'get me a dentist' with intent '{'name': 'inform', 'confidence': 0.9424940347671509}' and entities '[{'start': 9, 'end': 16, 'value': 'dentist', 'entity': 'specialist', 'confidence': 0.9915488283977238, 'extractor': 'CRFEntityExtractor'}]'
Logged UserUtterance - tracker now has 7 events
Current slot values: 
	specialist: dentist
Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'slot_specialist_0': 1.0, 'entity_specialist': 1.0, 'prev_action_listen': 1.0, 'intent_inform': 1.0}]
There is no memorised next action
Predicted next action using policy_0_KerasPolicy
Predicted next action 'action_appointment' with prob 0.32.
Calling action endpoint to run action 'action_appointment'.
Failed to run custom action 'action_appointment'. Couldn't connect to the server at 'http://localhost:5055/webhook'. Is the server running? Error: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f908c0fae80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/zoro/anaconda3/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/zoro/anaconda3/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/zoro/anaconda3/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/zoro/anaconda3/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/home/zoro/anaconda3/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 196, in connect
    conn = self._new_conn()
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f908c0fae80>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f908c0fae80>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/rasa_core/actions/action.py", line 382, in run
    json=json, method="post", timeout=DEFAULT_REQUEST_TIMEOUT)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/rasa_core/utils.py", line 702, in request
    **kwargs)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f908c0fae80>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/rasa_core/processor.py", line 345, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/rasa_core/actions/action.py", line 403, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Action 'action_appointment' ended with events '[]'
Current tracker state [{}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'slot_specialist_0': 1.0, 'entity_specialist': 1.0, 'prev_action_listen': 1.0, 'intent_inform': 1.0}, {'prev_action_appointment': 1.0, 'slot_specialist_0': 1.0, 'entity_specialist': 1.0, 'intent_inform': 1.0}]
There is no memorised next action
Predicted next action using policy_0_KerasPolicy
Predicted next action 'action_listen' with prob 0.86.
Action 'action_listen' ended with events '[]'
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
Looking for jobs to run
No jobs; waiting until a job is added
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Available web server routes: 
hello                                              HEAD, OPTIONS, GET             /
list_trackers                                      HEAD, OPTIONS, GET             /conversations
execute_action                                     OPTIONS, POST                  /conversations/[sender_id]/execute
log_message                                        OPTIONS, POST                  /conversations/[sender_id]/messages
predict                                            OPTIONS, POST                  /conversations/[sender_id]/predict
respond                                            HEAD, GET, OPTIONS, POST       /conversations/[sender_id]/respond
retrieve_story                                     HEAD, OPTIONS, GET             /conversations/[sender_id]/story
retrieve_tracker                                   HEAD, OPTIONS, GET             /conversations/[sender_id]/tracker
replace_events                                     PUT, OPTIONS                   /conversations/[sender_id]/tracker/events
get_domain                                         HEAD, OPTIONS, GET             /domain
evaluate_stories                                   OPTIONS, POST                  /evaluate
continue_training                                  OPTIONS, POST                  /finetune
load_model                                         OPTIONS, POST                  /model
parse                                              OPTIONS, POST                  /parse
tracker_predict                                    OPTIONS, POST                  /predict
static                                             HEAD, OPTIONS, GET             /static/[filename]
status                                             HEAD, OPTIONS, GET             /status
version                                            HEAD, OPTIONS, GET             /version
custom_webhook_CmdlineInput.health                 HEAD, OPTIONS, GET             /webhooks/rest/
custom_webhook_CmdlineInput.receive                OPTIONS, POST                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.9625009894371033}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 
	specialist: None
Current tracker state [None, None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '8'
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'utter_greet' with prob 1.00.
Action 'utter_greet' ended with events '[]'
Bot utterance 'BotUttered(text: Hi! What can I do for you?, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'get me a psychiatrist' with intent '{'name': 'inform', 'confidence': 0.9589043855667114}' and entities '[{'start': 9, 'end': 21, 'value': 'psychiatrist', 'entity': 'specialist', 'confidence': 0.9753705056668778, 'extractor': 'CRFEntityExtractor'}]'
Logged UserUtterance - tracker now has 7 events
Current slot values: 
	specialist: psychiatrist
Current tracker state [None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'prev_action_listen': 1.0, 'slot_specialist_0': 1.0, 'entity_specialist': 1.0, 'intent_inform': 1.0}]
There is no memorised next action
Predicted next action using policy_0_KerasPolicy
Predicted next action 'action_appointment' with prob 0.37.
Calling action endpoint to run action 'action_appointment'.
Failed to run custom action 'action_appointment'. Couldn't connect to the server at 'http://localhost:5055/webhook'. Is the server running? Error: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f77e81bad68>: Failed to establish a new connection: [Errno 111] Connection refused'))
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/zoro/anaconda3/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/zoro/anaconda3/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/zoro/anaconda3/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/zoro/anaconda3/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/home/zoro/anaconda3/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 196, in connect
    conn = self._new_conn()
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f77e81bad68>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f77e81bad68>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/rasa_core/actions/action.py", line 382, in run
    json=json, method="post", timeout=DEFAULT_REQUEST_TIMEOUT)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/rasa_core/utils.py", line 702, in request
    **kwargs)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f77e81bad68>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/rasa_core/processor.py", line 345, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/rasa_core/actions/action.py", line 403, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Action 'action_appointment' ended with events '[]'
Current tracker state [{}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'prev_action_listen': 1.0, 'slot_specialist_0': 1.0, 'entity_specialist': 1.0, 'intent_inform': 1.0}, {'slot_specialist_0': 1.0, 'prev_action_appointment': 1.0, 'entity_specialist': 1.0, 'intent_inform': 1.0}]
There is no memorised next action
Predicted next action using policy_0_KerasPolicy
Predicted next action 'action_listen' with prob 0.90.
Action 'action_listen' ended with events '[]'
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
Looking for jobs to run
No jobs; waiting until a job is added
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
Looking for jobs to run
No jobs; waiting until a job is added
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Available web server routes: 
hello                                              GET, HEAD, OPTIONS             /
list_trackers                                      GET, HEAD, OPTIONS             /conversations
execute_action                                     POST, OPTIONS                  /conversations/[sender_id]/execute
log_message                                        POST, OPTIONS                  /conversations/[sender_id]/messages
predict                                            POST, OPTIONS                  /conversations/[sender_id]/predict
respond                                            GET, POST, HEAD, OPTIONS       /conversations/[sender_id]/respond
retrieve_story                                     GET, HEAD, OPTIONS             /conversations/[sender_id]/story
retrieve_tracker                                   GET, HEAD, OPTIONS             /conversations/[sender_id]/tracker
replace_events                                     PUT, OPTIONS                   /conversations/[sender_id]/tracker/events
get_domain                                         GET, HEAD, OPTIONS             /domain
evaluate_stories                                   POST, OPTIONS                  /evaluate
continue_training                                  POST, OPTIONS                  /finetune
load_model                                         POST, OPTIONS                  /model
parse                                              POST, OPTIONS                  /parse
tracker_predict                                    POST, OPTIONS                  /predict
static                                             GET, HEAD, OPTIONS             /static/[filename]
status                                             GET, HEAD, OPTIONS             /status
version                                            GET, HEAD, OPTIONS             /version
custom_webhook_CmdlineInput.health                 GET, HEAD, OPTIONS             /webhooks/rest/
custom_webhook_CmdlineInput.receive                POST, OPTIONS                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.9625009894371033}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 
	specialist: None
Current tracker state [None, None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '9'
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'utter_greet' with prob 1.00.
Action 'utter_greet' ended with events '[]'
Bot utterance 'BotUttered(text: Hi! What can I do for you?, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_2_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'can i get an appointment with a dentist?' with intent '{'name': 'inform', 'confidence': 0.9523743391036987}' and entities '[{'start': 32, 'end': 39, 'value': 'dentist', 'entity': 'specialist', 'confidence': 0.9915882819109069, 'extractor': 'CRFEntityExtractor'}]'
Logged UserUtterance - tracker now has 7 events
Current slot values: 
	specialist: dentist
Current tracker state [None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'intent_inform': 1.0, 'entity_specialist': 1.0, 'prev_action_listen': 1.0, 'slot_specialist_0': 1.0}]
There is no memorised next action
Predicted next action using policy_0_KerasPolicy
Predicted next action 'action_appointment' with prob 0.37.
Calling action endpoint to run action 'action_appointment'.
Failed to run custom action 'action_appointment'. Couldn't connect to the server at 'http://localhost:5055/webhook'. Is the server running? Error: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae6448afd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/zoro/anaconda3/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/zoro/anaconda3/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/zoro/anaconda3/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/zoro/anaconda3/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/home/zoro/anaconda3/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 196, in connect
    conn = self._new_conn()
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fae6448afd0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae6448afd0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/rasa_core/actions/action.py", line 382, in run
    json=json, method="post", timeout=DEFAULT_REQUEST_TIMEOUT)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/rasa_core/utils.py", line 702, in request
    **kwargs)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fae6448afd0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/rasa_core/processor.py", line 345, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/zoro/anaconda3/lib/python3.7/site-packages/rasa_core/actions/action.py", line 403, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Action 'action_appointment' ended with events '[]'
Current tracker state [{}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'intent_inform': 1.0, 'entity_specialist': 1.0, 'prev_action_listen': 1.0, 'slot_specialist_0': 1.0}, {'intent_inform': 1.0, 'prev_action_appointment': 1.0, 'entity_specialist': 1.0, 'slot_specialist_0': 1.0}]
There is no memorised next action
Predicted next action using policy_0_KerasPolicy
Predicted next action 'action_listen' with prob 0.85.
Action 'action_listen' ended with events '[]'
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_appointment'. Couldn't connect to the server at 'http://localhost:5055/webhook'. Is the server running? Error: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8805ea358>: Failed to establish a new connection: [Errno 111] Connection refused'))
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_appointment'. Couldn't connect to the server at 'http://localhost:5055'. Is the server running? Error: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68dc07b198>: Failed to establish a new connection: [Errno 111] Connection refused'))
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_appointment'. Action server responded with a non 200 status code of 404. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 404 Client Error: NOT FOUND for url: http://localhost:5055/
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_appointment'. Action server responded with a non 200 status code of 404. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 404 Client Error: NOT FOUND for url: http://localhost:5055/
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_appointment'. Action server responded with a non 200 status code of 404. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 404 Client Error: NOT FOUND for url: http://localhost:5055/
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_appointment'. Action server responded with a non 200 status code of 404. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 404 Client Error: NOT FOUND for url: http://localhost:5055/
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_appointment'. Action server responded with a non 200 status code of 404. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 404 Client Error: NOT FOUND for url: http://localhost:5055/
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_appointment'. Action server responded with a non 200 status code of 404. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 404 Client Error: NOT FOUND for url: http://localhost:5055/
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_appointment'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restoring parameters from models/nlu/current/component_5_EmbeddingIntentClassifier.ckpt
Scheduler started
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_appointment'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to run custom action 'action_appointment'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
Scheduler started
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
Scheduler started
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_appointment'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
Scheduler started
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
Scheduler started
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/zoro/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
Generating grammar tables from /usr/lib/python3.6/lib2to3/Grammar.txt
Generating grammar tables from /usr/lib/python3.6/lib2to3/PatternGrammar.txt
Scheduler started
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_appointment'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
Generating grammar tables from /usr/lib/python3.6/lib2to3/Grammar.txt
Generating grammar tables from /usr/lib/python3.6/lib2to3/PatternGrammar.txt
Scheduler started
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_appointment'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to run custom action 'action_appointment'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
Generating grammar tables from /usr/lib/python3.6/lib2to3/Grammar.txt
Generating grammar tables from /usr/lib/python3.6/lib2to3/PatternGrammar.txt
Scheduler started
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
Generating grammar tables from /usr/lib/python3.6/lib2to3/Grammar.txt
Generating grammar tables from /usr/lib/python3.6/lib2to3/PatternGrammar.txt
Scheduler started
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
Generating grammar tables from /usr/lib/python3.6/lib2to3/Grammar.txt
Generating grammar tables from /usr/lib/python3.6/lib2to3/PatternGrammar.txt
Scheduler started
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_appointment'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to run custom action 'action_appointment'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
Generating grammar tables from /usr/lib/python3.6/lib2to3/Grammar.txt
Generating grammar tables from /usr/lib/python3.6/lib2to3/PatternGrammar.txt
Scheduler started
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_appointment'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to run custom action 'action_appointment'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
Generating grammar tables from /usr/lib/python3.6/lib2to3/Grammar.txt
Generating grammar tables from /usr/lib/python3.6/lib2to3/PatternGrammar.txt
Scheduler started
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_appointment'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to run custom action 'action_appointment'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
Generating grammar tables from /usr/lib/python3.6/lib2to3/Grammar.txt
Generating grammar tables from /usr/lib/python3.6/lib2to3/PatternGrammar.txt
Scheduler started
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
Generating grammar tables from /usr/lib/python3.6/lib2to3/Grammar.txt
Generating grammar tables from /usr/lib/python3.6/lib2to3/PatternGrammar.txt
Scheduler started
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_appointment'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to run custom action 'action_appointment'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_appointment'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Rasa process starting
Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
Generating grammar tables from /usr/lib/python3.6/lib2to3/Grammar.txt
Generating grammar tables from /usr/lib/python3.6/lib2to3/PatternGrammar.txt
Scheduler started
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/keras/backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
From /home/aditya/chatbot/my_env/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Rasa Core server is up and running on http://localhost:5005
